name: coxi_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython=1.86
  - pandas=2.3.3
  - numpy=2.2.6
  - scipy=1.15.2
  - scikit-learn=1.7.2
  - joblib